### ISSUE TITLE
Move to JuliaMath

### ISSUE THREAD

**Issue by ViralBShah** [JuliaMath/AppleAccelerate.jl#25]
@tkelman Can we move this to JuliaMath?

**Comment by tkelman** [comment]
Yes, will do, good spot. I invited @rprechelt to that organization. Will do a batch of these, I'm giving some "fair warning" notification time in the other cases.

**Comment by ViralBShah** [comment]
I think you can just move these.

**Comment by tkelman** [comment]
Fine, done.

**Comment by ViralBShah** [comment]
I assume you will be updating METADATA?

**Comment by tkelman** [comment]
Yes but it doesn't actually need to be done immediately since the github redirect will take care of it in the meantime. Just a housekeeping issue in case someone ever creates a new different JuliaLang/AppleAccelerate.jl repository, which would break the automatic redirect.
