### ISSUE TITLE
some functions got broken on the latest 13b7

### ISSUE THREAD

**Issue by mryodo** [JuliaMath/AppleAccelerate.jl#47]
Hi! Maybe, that's on my end, but...

After the update to the latest beta (beta7) of macos 13, the package throughs an error like `could not load symbol "vvsin"`

Minimal working example:

```julia
using AppleAccelerate
x = rand(10, 1);
AppleAccelerate.sin(x)
```

it throughs 
```
ERROR: could not load symbol "vvsin":
dlsym(0x39e90f318, vvsin): invalid handle
```

**Comment by alexgower** [comment]
I still have this exact issue
