### ISSUE TITLE
Failed Precompilation after Mac OS X Ventura Update - Could Not Load Symbosl "vvsin"

### ISSUE THREAD

**Issue by alexgower** [JuliaMath/AppleAccelerate.jl#51]
Since updating to Mac OS X Venture I get this issue when calling AppleAccelerate functions:

ERROR: could not load symbol "vvsin":
dlsym(0x3a2d8ff48, vvsin): invalid handle
Stacktrace:
  [1] dlsym(hnd::Ptr{Nothing}, s::String; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:59
  [2] dlsym
    @ ./libdl.jl:56 [inlined]
  [3] get_fptr
    @ ~/.julia/packages/AppleAccelerate/UAidl/src/AppleAccelerate.jl:13 [inlined]
  [4] sin!(out::Matrix{Float64}, X::Matrix{Float64})
    @ AppleAccelerate ~/.julia/packages/AppleAccelerate/UAidl/src/Array.jl:30

**Comment by ViralBShah** [comment]
I'm on Ventura too - but don't see this error - at least on the Intel macs.

**Comment by chenspc** [comment]
I have the save issue after a recent macos upgrade, although I was already on Ventura for a while and it was working just days ago (on M1 Max). 

I suspect #53 might also be related to this. Will the PR #52 be merged soon?

**Comment by alexgower** [comment]
I'm still having this issue on the M1 Macbook Air

**Comment by chenspc** [comment]
> I'm still having this issue on the M1 Macbook Air @ViralBShah

I think you may need to switch to the master branch (if you haven't done so already). It worked for me after the fix.

**Comment by ViralBShah** [comment]
Someone needs to tag a new version? Happy to add more folks to the org to help with the management of this package.
