### ISSUE TITLE
no library present

### ISSUE THREAD

**Issue by rveltz** [JuliaMath/AppleAccelerate.jl#53]
I am not sure if this is a newbie error but my files are like 

```
shell> ls /System/Library/Frameworks/Accelerate.framework/
Frameworks	Resources	Versions
```

Hence, this may be the reason why the following occurs. I am not sure why [AppleAccelerate](https://github.com/JuliaMath/AppleAccelerate.jl) does not error upon loading.

````
julia> @btime AppleAccelerate.exp($X);
ERROR: could not load symbol "vvexp":
```

**Comment by mzy2240** [comment]
Try `/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate`. Even if it did not show up in `ls`, it should be still accessible.

**Comment by rveltz** [comment]
it seems to work with this path

**Comment by ViralBShah** [comment]
Can you try master and reopen if it doesn't work?
