### ISSUE TITLE
Split LinearAlgebra capabilities from other Math capabilities

### ISSUE THREAD

**Issue by ViralBShah** [JuliaMath/AppleAccelerate.jl#60]
I think it would make sense to separate this into two packages, and move the BLAS/LAPACK into a separate package in JuliaLinearAlgebra called `AppleAccelerateLinalg` and keep this one as is (but it can depend on AppleAccelerateLinalg`).

Otherwise, people who want the BLAS capabilities also have to opt into all the other things this package provides. 

cc @staticfloat

**Comment by staticfloat** [comment]
I removed all the other stuff.  😏

**Comment by ViralBShah** [comment]
While extremely unlikely, wouldn't that break people's codes if they were using this package? At the very least, should we move those capabilities to a separate package?

**Comment by ViralBShah** [comment]
@staticfloat I'm happy to attempt creating a new package out of your PR. Is that ok?

**Comment by staticfloat** [comment]
Sure

**Comment by staticfloat** [comment]
Although it should be noted for the record that there are zero known dependents on this package: https://juliahub.com/ui/Packages/AppleAccelerate/9G3ko/0.3.3?page=2

**Comment by ViralBShah** [comment]
But people probably use it directly, and it would be nice to actually grow those capabilities to cover the rest of Accelerate.

**Comment by ViralBShah** [comment]
Thinking further, a separate package feels like too much work. Can we just reinstate the rest of the Accelerate wrappers here so that we don't lose them, and someone can take that work forward in the future?

**Comment by ViralBShah** [comment]
I've updated #58 to reinstate the earlier functionality.
